name: Update Package Index

on: 
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List .tar.xz files and update package.index
      run: |
        find . -name "*.tar.xz" -exec basename {} \; > package.index
        cat package.index

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add package.index
        git commit -m 'Update package index'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
